server:
  port: 8081
spring:
  profiles:
    include: migration
  jpa:
    legacy-ad:
      hikari:
        maximum-pool-size: 50
    recent-ad:
      hikari:
        maximum-pool-size: 50
  cloud:
    stream:
      binders:
        legacy-rabbit:
          type: rabbit
          environment:
            spring.rabbitmq:
              host: localhost
              port: 5673
              username: ruser
              password: localpw
              virtual-host: legacy
      bindings:
        legacyConsumer-in-0:
          binder: legacy-rabbit
          destination: legacy-topic
          group: migration
logging:
  file:
    name: logs/gradual.log