spring:
  jpa:
    legacy-ad:
      hikari:
        jdbc-url: jdbc:mysql://localhost:3309/legacy-ad
        username: root
        password: localpw
        maximum-pool-size: 50
      properties:
        hibernate:
          hbm2ddl.auto: update
          show_sql: true
          physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  cloud:
    stream:
      binders:
        legacy-rabbit:
          type: rabbit
          environment:
            spring.rabbitmq:
              host: localhost
              port: 5673
              username: ruser
              password: localpw
              virtual-host: legacy
      bindings:
        legacy-rabbit-out:
          binder: legacy-rabbit
          destination: legacy-topic